#!/usr/bin/env bash
# Bash script that transers a file from client to the server
# It accepts path to the file, ip of the remote server, the user name & path
# to the SSH private key using scp(secure copy)

if [ $# -lt 4 ]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
fi
