#!/usr/bin/env bash
# Bash script that install & configure HAproxy

# Add HAproxy to the repository
apt install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.5

# update the package
apt update

#instal haproxy
apt install -y haproxy=1.5.\*

# take the backup of the original haproxy.cfg & create a new file
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

# configure haproxy
printf %s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
	log global
	mode http
	option httplog
	option dontlognull
	option redispatch
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
        stats uri /haproxy?stats
	default_backend http_rear

backend http_rear
	balance roundrobin
	server 204-web-02 35.237.151.121:80 check
	server 204-web-01 34.75.251.99:80  check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
