#!/usr/bin/env bash
#bash script to display FizzBuzz play

i=1
while ((i <= 100))
do
	if [ $((i % 3)) -eq 0 -a $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 -a $((i % 5)) -ne 0 ]
	then 
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 -a $((i % 3)) -ne 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
    	i=$((i + 1))
done
