#!/usr/bin/env bash
#bash script to read content of the given file and tell story

fname="/etc/passwd"
while IFS=: read -r usrname password uid gid fname home path
do
	echo "The user $usrname is part of the $gid gang,"\
	"lives in $home and rides $path. $uid's place is"\
	" protected by the passcode $password, more info"\
	" about the user here: $fname"
done < $fname
