#!/usr/bin/env bash
#bash script to display bad, good luck and holberton school based on condition

i=1
while ((i <= 10))
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
    	i=$((i + 1))
done
