#!/usr/bin/env bash
#bash script to display bad luck from china, japan, Itally and a number

i=1
while ((i <= 20))
do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
    	i=$((i + 1))
done
